plugin 'cocoapods-user-defined-build-types'
enable_user_defined_build_types!
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'whitehaxBackup' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  target 'whitehaxBackupTests' do
    inherit! :complete
    # Pods for testing
  end
  pod "MMLanScan", :build_type => :dynamic_framework
  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  
end

target 'whitehaxBackup-tvOS' do
  # Pods for whitehaxBackup-tvOS

  target 'whitehaxBackup-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
